# 规则集合并配置
# merged-rules/[Strategy]/[Type]/[Owner]/[Filename]
# merged-rules/ [策略Strategy] / [类型Type] / [作者Owner] / [文件.txt]
merges:
  # 示例：需要合并的情况
  - strategy: "block"
    type: "domain"
    owner: "rksk102"
    filename: "all-adblock.txt"
    description: "合并多个广告拦截列表"
    inputs:
      - "block/domain/DustinWin/ads.txt"
      - "block/domain/MetaCubeX/category-ads-all.txt"
      - "block/domain/Loyalsoldier/reject-list.txt"

  - strategy: "direct"
    type: "ipcidr"
    owner: "rksk102"
    filename: "all-cnip.txt"
    description: "所有直连cnipcidr"
    inputs:
      - "direct/ipcidr/Loyalsoldier/cncidr.txt"
      - "direct/ipcidr/MetaCubeX/cn.txt"

  - strategy: "proxy"
    type: "domain"
    owner: "rksk102"
    filename: "all-proxy.txt"
    description: "代理域名规则"
    inputs:
      - "proxy/domain/Loyalsoldier/proxy.txt"
      - "proxy/domain/Loyalsoldier/proxy-list.txt"
